language: php

php:
  - 5.6
  - 7

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script: vendor/bin/phpunit --verbose

sudo: false

matrix:
  fast_finish: true